schema_version = "1.0.0"

id = "pataz_notes"
version = "5.1.0"
name = "Pataz Notes"
tagline = "Anotate your blend files"
maintainer = "Daniel Salazar"
type = "add-on"

website = "https://github.com/ZanQdo/notes"

tags = ["Pipeline"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 Daniel Salazar",]

